name: minecraft-server-stack
services:
  paper-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8080:8080"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.11"
      MEMORY: "2G"
    volumes:
      - ./server-data:/data
    depends_on:
      sebutils-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 25565"]
      interval: 30s
      timeout: 10s
      retries: 3
  sebutils-database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sebutils
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sebutils
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sebutils -d sebutils"]
      interval: 3s
      timeout: 5s
      retries: 5
  